/**
 * Live dashboard for the Node host. Serves the main HTML page, per-session
 * detail pages, and JSON polling endpoints. All "/api/*.json" endpoints
 * recompute from disk on every request — pixelpipe doesn't have a query
 * layer, but a 1.5 MB JSONL streams in well under 100 ms.
 *
 * Legacy live-poll endpoints (left in place, the existing tick() loop uses
 * them):
 *
 *   GET  /, /dashboard               → main HTML page
 *   GET  /proxy-stats                → JSON aggregate over the in-mem ring
 *   GET  /proxy-recent               → JSON ring buffer of recent requests
 *   GET  /proxy-latest-png[?crop=N]  → raw PNG of the latest rendered image
 *
 * New session / cleanup endpoints (added in this PR):
 *
 *   GET  /sessions/${id}             → HTML detail page for one session
 *   GET  /api/sessions.json          → grouped sessions (sha8 + project + counts)
 *   GET  /api/sessions/${id}.json    → events + metadata for one session
 *   GET  /api/disk.json              → events.jsonl + 4xx-bodies disk usage
 *   GET  /api/stats.json             → full-history aggregate (formerly `pixelpipe stats`)
 *   POST /api/sessions/prune         → atomic prune by older-than / keep-last / session
 *
 * Metric formulas and HTML shell originally ported from the Python reference
 * implementation (deleted after live cache-rate validation hit 98.7% by tokens).
 *
 * Node-only by design. Workers host has no dashboard; use Workers Logs.
 *
 * Memory bound: ring buffer cap 50 events + ONE latest PNG (replaced on each
 * compressed request). At a typical 75 KB PNG that's well under 1 MB resident.
 */

import * as fs from 'node:fs';
import * as readline from 'node:readline';
import type { ProxyEvent } from './core/proxy.js';
import type { TrackEvent } from './core/tracker.js';
import {
  computeActualInputEff,
  computeBaselineInputEff,
} from './core/baseline.js';
import {
  aggregateSessions,
  claudeCodeMap,
  collectSessionEvents,
  diskUsage,
  filterSessions,
  prune,
  redactEvent,
  type ClaudeCodeSessionRef,
  type ListOptions,
  type PruneOptions,
  type SessionsPaths,
  type SessionSummary,
} from './sessions.js';
import { aggregateEventsFile, summaryToJson } from './stats.js';
// Compiled Svelte UI - generated by `scripts/build-dashboard-ui.mjs`.
// Importing the .ts source lets esbuild inline the bundle string when it
// compiles `src/node.ts`. The generated file is committed so a clean install
// works without a separate UI build step at install time.
import { DASHBOARD_JS } from './dashboard-bundle.js';

const RECENT_CAP = 50;

/** One row in the dashboard's "recent requests" table. Compact on purpose —
 *  this lives in memory and gets serialized on every poll.
 *
 *  The "input" numbers (`actual_input`, `baseline_input`) are input-side
 *  only — input + cache_create×1.25 + cache_read×0.10 — because that's
 *  the slice the proxy can move. `output_tokens` is reported separately so
 *  the operator can see what fraction of the bill is unaffected by
 *  compression (and decide whether the headline % makes sense for their
 *  workload). */
export interface RecentRow {
  ts: number;
  method: string;
  path: string;
  status: number;
  size_in?: number;
  compressed: boolean;
  cc_added?: number;
  input_tokens?: number;
  /** From /v1/messages `usage.output_tokens`. Identical with/without
   *  compression — shown so the operator can see why an output-heavy
   *  turn moves the headline less than a cache-create-heavy one. */
  output_tokens?: number;
  cache_create?: number;
  cache_read?: number;
  /** input + cache_create×1.25 + cache_read×0.10, from the upstream usage
   *  block. Missing when the request 4xx'd or wasn't /v1/messages. */
  actual_input?: number;
  /** /v1/messages/count_tokens(originalBody).input_tokens. Missing when the
   *  side-probe failed or the request body wasn't an Anthropic Messages payload. */
  baseline_input?: number;
  /** How much the running "saved" total moved on this request. */
  session_saved_so_far_delta?: number;
}

/** Aggregate over the whole session. Reset on process restart unless
 *  replay() is called to seed from the JSONL file.
 *
 *  The savings numerator is input-only — output is identical with and
 *  without compression, so it cancels. The denominator is the FULL bill
 *  (input + output×5 in input-token-equivalents) so the headline percentage
 *  drops honestly toward zero on output-heavy workloads instead of hiding
 *  the fact that the proxy only moves part of the cost.
 *
 *    Per event (see src/core/baseline.ts for the derivation):
 *      cacheable = baseline_cacheable_tokens || 0     (tokens up to last cache_control)
 *      cold_tail = baseline_tokens − cacheable        (always-cold input on both paths)
 *      cc_u, cr_u = the unproxied path's counterfactual cache_create / cache_read split:
 *                   cr > 0 ?  cc_u = min(cc, cacheable),  cr_u = cacheable − cc_u   (warm turn)
 *                 : cc > 0 ?  cc_u = cacheable,           cr_u = 0                  (cold start)
 *                 :           cc_u = 0,                   cr_u = 0                  (no caching)
 *      baseline_input_eff = cc_u × 1.25 + cr_u × 0.10
 *                         + (cacheable − cc_u − cr_u) × 1.0 + cold_tail × 1.0
 *      actual_input_eff   = input + cache_create×1.25 + cache_read×0.10
 *      output_equiv       = output × 5                (input-token-equivalent at the 5× output rate)
 *      saved              = baseline_input_eff − actual_input_eff
 *      baseline_total     = baseline_input_eff + output_equiv
 *      actual_total       = actual_input_eff + output_equiv
 *
 *    Roll-up:
 *      saved_pct = Σ saved / Σ baseline_total × 100
 *
 *  This is what Anthropic's weekly-limit meter actually counts — input +
 *  output×5 in input-token-equivalents. The dashboard headline matches it
 *  so a "20% saved" number means weekly-limit consumption dropped by 20%,
 *  not "20% off the slice we touched while the other half stayed full." */
interface Totals {
  requests: number;
  compressedRequests: number;
  /** Sum of weighted actual input tokens we paid for, across all events that
   *  also carried a baseline_tokens measurement (input + cache_create×1.25 +
   *  cache_read×0.10). */
  actualInputWeighted: number;
  /** Sum of the cache-aware baseline (see formula above) across the same
   *  events that contributed to `actualInputWeighted`. The honest counter-
   *  factual cost of the unproxied path. */
  baselineInputWeighted: number;
  /** Sum of output_tokens × OUTPUT_TOKEN_RATE across the same events. Added
   *  to BOTH sides of the savings math denominator so the headline % counts
   *  output toward the total bill (it cancels in the numerator — proxy
   *  doesn't touch output). Without this the headline ignores half the
   *  bill on output-heavy sessions. */
  outputWeighted: number;
  /** Sum of ground-truth output character counts from the SSE/JSON scanner
   *  (see `OutputMeasurement` in proxy.ts). These three accumulators are
   *  independent of Anthropic's `usage.output_tokens` — they let the operator
   *  compare what we measured vs what Anthropic billed and surface the gap
   *  the redacted_thinking opaque blocks create. Counted in Unicode code
   *  units (UTF-16 string .length). */
  textCharsMeasured: number;
  thinkingCharsMeasured: number;
  toolUseCharsMeasured: number;
  /** Number of `redacted_thinking` content blocks we saw. We can't read
   *  their length (server-encrypted bytes) so we count blocks instead. */
  redactedBlockCountMeasured: number;
  /** How many events contributed measurement counters. Lets the UI annotate
   *  the panel ("N of M events measured") when the scanner fell back. */
  eventsWithMeasurement: number;
  startedAt: number;
}

/*
 * ─────────────────────────────────────────────────────────────────────────
 *  PROVENANCE — every magic number below should trace to one of these:
 *
 *  [docs-pricing]   docs.anthropic.com/en/docs/about-claude/pricing
 *                   Verified 2026-05-19 via WebFetch. The page lists per-model
 *                   per-million-token rates and the cache-tier multipliers.
 *
 *  [count_tokens]   docs.anthropic.com/en/api/messages-count-tokens
 *                   The dashboard's baseline number comes from a free side
 *                   call to /v1/messages/count_tokens on the PRE-COMPRESSION
 *                   body. No estimation, no α, no regression.
 * ─────────────────────────────────────────────────────────────────────────
 */

/** Output-token rate multiplier (referenced to the input base rate).
 *  Source: [docs-pricing] — Opus 4.7 lists $5/Mtok input and $25/Mtok
 *  output (5×); Sonnet 4.7 lists $3/Mtok input and $15/Mtok output (5×).
 *  Same ratio holds on Haiku 4.5 ($1/$5). */
const OUTPUT_TOKEN_RATE = 5.0;

/** Per-million-token input rate ASSUMED for the headline dollar figure.
 *  Source: https://docs.claude.com/en/docs/about-claude/pricing — Opus 4.7
 *  input is $5/Mtok (same as Opus 4.5 / 4.6; the previous "$2.50" value
 *  here was a regression). Cache-write 5m = $6.25/Mtok (1.25×),
 *  cache-read = $0.50/Mtok (0.10×).
 *
 *  This is exposed on /proxy-stats as `pricing_assumptions.input_per_mtok`
 *  so the operator can see what we assumed and override if they're
 *  running against a non-default deployment (Bedrock/Vertex add a 10%
 *  premium; Sonnet would be $3/Mtok, etc.).
 *
 *  NOTE: Opus 4.7 uses a different tokenizer than 4.5/4.6 (per
 *  docs.claude.com/en/docs/about-claude/pricing), so even at the same
 *  $/Mtok rate, the same string maps to a different token count. The
 *  honest oracle for "tokens in this body" is `count_tokens` against the
 *  actual target model; do not trust hardcoded chars-per-token or
 *  tokens-per-image constants on 4.7 without verifying against the
 *  upstream probe. */
const ASSUMED_INPUT_USD_PER_MTOK = 5.0;

export class DashboardState {
  private recent: RecentRow[] = [];
  private totals: Totals = {
    requests: 0,
    compressedRequests: 0,
    actualInputWeighted: 0,
    baselineInputWeighted: 0,
    outputWeighted: 0,
    textCharsMeasured: 0,
    thinkingCharsMeasured: 0,
    toolUseCharsMeasured: 0,
    redactedBlockCountMeasured: 0,
    eventsWithMeasurement: 0,
    startedAt: Date.now() / 1000,
  };
  private latestPng: Uint8Array | null = null;
  private latestPngMeta = '';
  private latestPngWidth = 0;
  private latestPngHeight = 0;
  /** Runtime kill switch for compression. When false, the proxy forwards
   *  /v1/messages unchanged to upstream — pure passthrough, no images,
   *  no transforms. Controlled by the dashboard "passthrough" toggle so
   *  the operator can disable the proxy's transform instantly when
   *  upstream is unhealthy or when triaging a bad release. In-memory
   *  only — restart resets to true. */
  private compressionEnabled = true;
  setCompressionEnabled(on: boolean): void {
    this.compressionEnabled = on;
  }
  getCompressionEnabled(): boolean {
    return this.compressionEnabled;
  }
  /** Resolved disk paths for the events.jsonl + 4xx-bodies sidecar dir. The
   *  new sessions / cleanup endpoints need this; legacy callers that don't
   *  pass `paths` opt out of those endpoints by returning 503. */
  private readonly paths: SessionsPaths | undefined;

  /** Test hook: when set, /api/sessions.json and /api/sessions/${id}.json
   *  call this instead of `claudeCodeMap()` with the real `~/.claude/projects/`
   *  path. Lets unit tests run in tens of ms instead of scanning hundreds of
   *  the developer's actual Claude Code session files. */
  private readonly ccMapFn: () => Promise<Map<string, ClaudeCodeSessionRef>>;

  constructor(
    paths?: SessionsPaths,
    ccMapFn?: () => Promise<Map<string, ClaudeCodeSessionRef>>,
  ) {
    this.paths = paths;
    this.ccMapFn = ccMapFn ?? (() => claudeCodeMap());
  }

  /** Stash the latest rendered image (called from onRequest with the raw
   *  ProxyEvent before info.firstImagePng is dropped by toTrackEvent). */
  captureImage(info: NonNullable<ProxyEvent['info']>): void {
    if (!info.firstImagePng) return;
    this.latestPng = info.firstImagePng;
    this.latestPngWidth = info.firstImageWidth ?? 0;
    this.latestPngHeight = info.firstImageHeight ?? 0;
    const kb = (info.firstImagePng.length / 1024).toFixed(1);
    this.latestPngMeta =
      `${this.latestPngWidth}×${this.latestPngHeight} · ${kb} KB · ` +
      `${info.imageCount ?? 0} image${info.imageCount === 1 ? '' : 's'} total`;
  }

  /** Fold one event into the running totals + ring buffer.
   *
   *  Savings math is gated on a per-request `baseline_tokens` measurement
   *  from the parallel count_tokens probe AND an upstream usage block.
   *  When either is missing, we still count the request but skip its
   *  savings contribution — no estimation. */
  update(ev: ProxyEvent): void {
    // Stash the image bytes before they get GC'd by the request finishing.
    if (ev.info) this.captureImage(ev.info);

    const u = ev.usage;
    const info = ev.info;
    const compressed = info?.compressed === true;

    const inp = u?.input_tokens ?? 0;
    const out = u?.output_tokens ?? 0;
    const cc = u?.cache_creation_input_tokens ?? 0;
    const cr = u?.cache_read_input_tokens ?? 0;
    const haveUsage = u !== undefined && (inp > 0 || out > 0 || cc > 0 || cr > 0);
    const baseline = info?.baselineTokens;
    // Honest gating: only attribute savings when BOTH baseline probes
    // resolved (status === 'ok'). When the cacheable-prefix probe failed
    // (status === 'partial') we previously fell through to cacheable=0,
    // which silently charges the unproxied counterfactual the cold-input
    // rate on tokens that actually would have been cache-discounted —
    // fabricating "$ saved". Excluding the row is the only honest move
    // until the probe succeeds.
    const probeOk = info?.baselineProbeStatus === 'ok'
      // Back-compat: hosts that haven't adopted baselineProbeStatus yet
      // still see fields land; we accept legacy rows where the full-body
      // probe resolved AND (either no markers existed OR cacheable did too).
      || (info?.baselineProbeStatus === undefined && baseline !== undefined && baseline > 0);
    const haveBaseline = typeof baseline === 'number' && baseline > 0 && probeOk;

    // Weighted INPUT cost we actually paid this turn.
    const actualInputEff = haveUsage ? computeActualInputEff(inp, cc, cr) : 0;

    // Cache-aware baseline: decompose the unproxied counterfactual into
    // (cacheable_prefix, cold_tail) using the second count_tokens probe,
    // then split the prefix into (cc_u, cr_u) using the SAME absolute
    // cc bucket the proxied path paid this turn — because user-typed
    // content (the new tail that becomes cc) is NOT compressed, so its
    // absolute token count is approximately the same on both paths.
    // See src/core/baseline.ts for the full derivation and the May-2026
    // regression that motivated the rewrite.
    const baselineInputEff =
      haveBaseline && haveUsage
        ? computeBaselineInputEff(
            baseline,
            info?.baselineCacheableTokens ?? 0,
            cc,
            cr,
          )
        : 0;

    // Output tokens are identical with/without compression — the proxy never
    // touches the response body. They show up on BOTH sides of the savings
    // ratio at their actual rate (OUTPUT_TOKEN_RATE × input rate) so the
    // denominator reflects the full bill the user actually pays. Without
    // this, an output-heavy turn would silently inflate the "saved %"
    // headline relative to what Anthropic's weekly limit meters as token
    // consumption (input + output × 5).
    const outputEquiv = haveUsage ? out * OUTPUT_TOKEN_RATE : 0;

    this.totals.requests += 1;
    if (compressed) this.totals.compressedRequests += 1;

    if (haveBaseline && haveUsage) {
      this.totals.baselineInputWeighted += baselineInputEff;
      this.totals.actualInputWeighted += actualInputEff;
      this.totals.outputWeighted += outputEquiv;
    }

    // Measurement totals are independent of usage/baseline gating — they
    // accumulate whenever the scanner produced numbers. The scanner sets
    // measurement to undefined on 5xx (no body to scan) and on unknown
    // content-types; we count an event as "measured" when it has any.
    const m = ev.measurement;
    if (m) {
      this.totals.textCharsMeasured += m.textChars;
      this.totals.thinkingCharsMeasured += m.thinkingChars;
      this.totals.toolUseCharsMeasured += m.toolUseChars;
      this.totals.redactedBlockCountMeasured += m.redactedBlockCount;
      this.totals.eventsWithMeasurement += 1;
    }

    const row: RecentRow = {
      ts: Date.now() / 1000,
      method: ev.method,
      path: ev.path,
      status: ev.status,
      compressed,
      cc_added: compressed ? 1 : undefined,
      input_tokens: haveUsage ? inp : undefined,
      output_tokens: haveUsage ? out : undefined,
      cache_create: haveUsage ? cc : undefined,
      cache_read: haveUsage ? cr : undefined,
      actual_input: haveUsage ? round1(actualInputEff) : undefined,
      baseline_input: haveBaseline && haveUsage ? round1(baselineInputEff) : undefined,
      session_saved_so_far_delta:
        haveBaseline && haveUsage ? round1(baselineInputEff - actualInputEff) : undefined,
    };
    this.recent.push(row);
    if (this.recent.length > RECENT_CAP) this.recent.splice(0, this.recent.length - RECENT_CAP);
  }


  /** On startup, fold the last N entries from the JSONL events file back
   *  into the ring buffer so a process restart doesn't show an empty table.
   *  Cumulative totals are *not* restored (the file may have rotated, and
   *  double-counting is worse than starting fresh). */
  async replay(filePath: string): Promise<void> {
    try {
      await fs.promises.access(filePath, fs.constants.R_OK);
    } catch {
      return; // no file yet, nothing to replay
    }
    const stream = fs.createReadStream(filePath, { encoding: 'utf8' });
    const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
    const tail: TrackEvent[] = [];
    for await (const line of rl) {
      if (!line) continue;
      try {
        const ev = JSON.parse(line) as TrackEvent;
        tail.push(ev);
        if (tail.length > RECENT_CAP) tail.shift();
      } catch {
        /* skip malformed line */
      }
    }
    for (const t of tail) {
      const inp = t.input_tokens ?? 0;
      const out = t.output_tokens ?? 0;
      const cc = t.cache_create_tokens ?? 0;
      const cr = t.cache_read_tokens ?? 0;
      const haveUsage = inp > 0 || out > 0 || cc > 0 || cr > 0;
      const baseline = (t as { baseline_tokens?: number }).baseline_tokens;
      const cacheable = (t as { baseline_cacheable_tokens?: number })
        .baseline_cacheable_tokens ?? 0;
      const probeStatus = (t as { baseline_probe_status?: string }).baseline_probe_status;
      // Same gating rule as update(): require an explicit 'ok' status when
      // present; fall back to "have a baseline number" for legacy JSONL.
      const probeOk = probeStatus === 'ok'
        || (probeStatus === undefined && typeof baseline === 'number' && baseline > 0);
      const haveBaseline = typeof baseline === 'number' && baseline > 0 && probeOk;
      const actualInputEff = haveUsage ? computeActualInputEff(inp, cc, cr) : 0;
      const baselineInputEff =
        haveBaseline && haveUsage
          ? computeBaselineInputEff(baseline as number, cacheable, cc, cr)
          : 0;
      // Output tokens land in the row for the table; totals are not
      // restored on replay (see header comment on cumulative totals).
      const row: RecentRow = {
        ts: Date.parse(t.ts) / 1000,
        method: t.method,
        path: t.path,
        status: t.status,
        compressed: t.compressed === true,
        cc_added: t.compressed === true ? 1 : undefined,
        input_tokens: t.input_tokens,
        output_tokens: t.output_tokens,
        cache_create: t.cache_create_tokens,
        cache_read: t.cache_read_tokens,
        actual_input: haveUsage ? round1(actualInputEff) : undefined,
        baseline_input:
          haveBaseline && haveUsage ? round1(baselineInputEff) : undefined,
      };
      this.recent.push(row);
    }
  }

  // ---- HTTP handlers ------------------------------------------------------

  serveStats(): Response {
    // Two headline numbers, derived from the same per-event accumulators:
    //
    //   saved_pct_input_only = Σ saved / Σ baseline_input_eff × 100
    //     What the proxy actually saved on the slice it can move (input).
    //     Numerator = input tokens we didn't pay for (cache-aware).
    //     Denominator = input tokens we WOULD have paid (cache-aware).
    //     Output is excluded because the proxy doesn't touch it.
    //
    //   saved_pct_of_total_bill = Σ saved / Σ (baseline_input + output × 5) × 100
    //     What share of the TOTAL bill the proxy saved. Honest counter to the
    //     input-only number: on output-heavy sessions (long thinking blocks,
    //     big edits) the percentage shrinks because output dominates.
    //
    //   token_equivalent_total = Σ (actual_input + output × 5)
    //     What Anthropic's weekly limit actually meters — input × 1.0 +
    //     output × 5.0 (the same ratio as the per-MTok price card). This is
    //     the number that moves your "%% used this week" indicator.
    const baseline = this.totals.baselineInputWeighted;
    const actual = this.totals.actualInputWeighted;
    const output = this.totals.outputWeighted; // already × OUTPUT_TOKEN_RATE
    const saved = baseline - actual;
    const pctInput = baseline > 0 ? (saved / baseline) * 100 : 0;
    const baselineTotal = baseline + output;
    const actualTotal = actual + output;
    const pctTotal = baselineTotal > 0 ? (saved / baselineTotal) * 100 : 0;
    const uptimeSec = Date.now() / 1000 - this.totals.startedAt;
    const payload = {
      requests: this.totals.requests,
      compressed_requests: this.totals.compressedRequests,
      baseline_input_weighted: Math.round(baseline),
      actual_input_weighted: Math.round(actual),
      saved_input_tokens: Math.round(saved),
      // saved_pct kept for back-compat with existing dashboard HTML; it is
      // the input-only number. New code should read saved_pct_input_only.
      saved_pct: round1(pctInput),
      saved_pct_input_only: round1(pctInput),
      saved_pct_of_total_bill: round1(pctTotal),
      saved_usd: round4((saved * ASSUMED_INPUT_USD_PER_MTOK) / 1e6),
      output_weighted: Math.round(output),
      baseline_token_equivalent: Math.round(baselineTotal),
      actual_token_equivalent: Math.round(actualTotal),
      pricing_assumptions: {
        input_per_mtok: ASSUMED_INPUT_USD_PER_MTOK,
        output_multiplier: OUTPUT_TOKEN_RATE,
        cache_write_5m_multiplier: 1.25,
        cache_write_1h_multiplier: 2.0,
        cache_read_multiplier: 0.1,
        source: 'docs.anthropic.com/en/docs/about-claude/pricing (verified 2026-05-19)',
      },
      // Honest output measurement — char counts from the SSE/JSON scanner,
      // independent of Anthropic's `usage.output_tokens`. Surfaces the gap
      // the May-2026 weekly-meter audit hypothesized (redacted_thinking adds
      // billed tokens that we can't see). `events_with_measurement` lets the
      // operator weigh how representative the numbers are; when it's near
      // `requests`, the gap is real. When it's 0, the scanner never landed
      // (5xx-heavy session, no /v1/messages traffic).
      measured_text_chars: this.totals.textCharsMeasured,
      measured_thinking_chars: this.totals.thinkingCharsMeasured,
      measured_tool_use_chars: this.totals.toolUseCharsMeasured,
      measured_redacted_block_count: this.totals.redactedBlockCountMeasured,
      events_with_measurement: this.totals.eventsWithMeasurement,
      uptime_sec: uptimeSec,
      compression_enabled: this.compressionEnabled,
    };
    return new Response(JSON.stringify(payload, null, 2), {
      headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*' },
    });
  }

  serveRecent(): Response {
    const payload = {
      recent: this.recent,
      has_preview: this.latestPng !== null,
      preview_meta: this.latestPngMeta,
    };
    return new Response(JSON.stringify(payload), {
      headers: { 'content-type': 'application/json', 'access-control-allow-origin': '*' },
    });
  }

  servePng(): Response {
    // Cropping is done client-side via CSS (object-position + overflow:hidden).
    // Python decoded the PNG to crop server-side; we skip that to avoid
    // pulling a PNG decoder back in — the CSS approach renders identically.
    if (!this.latestPng) {
      return new Response('no image yet', { status: 404 });
    }
    return new Response(this.latestPng as unknown as BodyInit, {
      headers: { 'content-type': 'image/png', 'cache-control': 'no-cache' },
    });
  }

  serveHtml(port: number): Response {
    return new Response(DASHBOARD_HTML.replace(/__PORT__/g, String(port)), {
      headers: { 'content-type': 'text/html; charset=utf-8' },
    });
  }

  // ---- session / cleanup endpoints --------------------------------------
  //
  // Every endpoint below recomputes from disk on demand. The dashboard polls
  // these on a 5s cadence, which is fine for a single-user dev tool — even at
  // ~3k events / 1.5 MB the round-trip is <100ms on a warm SSD.

  /** GET /api/sessions.json — grouped sessions enriched with the Claude Code
   *  cross-reference. The body is paged via top-level `sessions` array; the
   *  client renders the table row-by-row. */
  async serveSessionsJson(opts: ListOptions = {}): Promise<Response> {
    if (!this.paths) return notConfigured('sessions');
    const [{ sessions }, ccMap] = await Promise.all([
      aggregateSessions(this.paths),
      this.ccMapFn(),
    ]);
    const rows = filterSessions(sessions, opts);
    const enriched = rows.map((s) => ({
      ...s,
      claudeCode: ccMap.get(s.id) ?? null,
    }));
    return jsonResponse({ sessions: enriched, count: enriched.length });
  }

  /** GET /api/sessions/${id}.json — events for one session + its Claude Code
   *  ref. Bodies are redacted by default (set ?include_bodies=1 to opt in). */
  async serveSessionJson(
    id: string,
    includeBodies: boolean,
  ): Promise<Response> {
    if (!this.paths) return notConfigured('session detail');
    const [events, ccMap] = await Promise.all([
      collectSessionEvents(this.paths, id),
      this.ccMapFn(),
    ]);
    if (events.length === 0) {
      return jsonResponse({ error: 'session not found', id }, 404);
    }
    return jsonResponse({
      id,
      claudeCode: ccMap.get(id) ?? null,
      includeBodies,
      events: events.map((e) => redactEvent(e, includeBodies)),
    });
  }

  /** GET /sessions/${id} — HTML detail page (uses /api/sessions/${id}.json). */
  serveSessionHtml(id: string, port: number): Response {
    const html = SESSION_DETAIL_HTML.replace(/__PORT__/g, String(port)).replace(
      /__SESSION_ID__/g,
      escapeHtml(id),
    );
    return new Response(html, {
      headers: { 'content-type': 'text/html; charset=utf-8' },
    });
  }

  /** GET /api/disk.json — current on-disk usage. */
  serveDiskJson(): Response {
    if (!this.paths) return notConfigured('disk usage');
    const d = diskUsage(this.paths);
    return jsonResponse({ ...d, paths: this.paths });
  }

  /** GET /api/stats.json — full-history aggregate. Migrated from the
   *  former `pixelpipe stats` CLI. */
  async serveApiStats(): Promise<Response> {
    if (!this.paths) return notConfigured('stats');
    const result = await aggregateEventsFile(this.paths.eventsFile);
    if (!result) {
      return jsonResponse({
        error: 'no events file yet',
        path: this.paths.eventsFile,
      }, 404);
    }
    return jsonResponse({
      parsed: result.parsed,
      dropped: result.dropped,
      summary: summaryToJson(result.summary),
    });
  }

  /** POST /api/sessions/prune — destructive but confirmed client-side. The
   *  client UI shows a `confirm()` dialog before calling this with
   *  `force: true`. We still default force=false at the wire level. */
  async handlePrune(body: PruneOptions): Promise<Response> {
    if (!this.paths) return notConfigured('prune');
    const report = await prune(this.paths, {
      force: body.force === true,
      olderThanDays: body.olderThanDays,
      keepLast: body.keepLast,
      sessionId: body.sessionId,
      sessionIds: Array.isArray(body.sessionIds) ? body.sessionIds : undefined,
    });
    return jsonResponse(report);
  }

  /** POST /api/compression — flip the runtime kill switch.
   *  Body: { enabled: boolean }. Returns the new state. In-memory only;
   *  restart resets to true. */
  handleCompressionToggle(body: { enabled?: unknown }): Response {
    const on = body.enabled === true;
    this.compressionEnabled = on;
    return jsonResponse({ compression_enabled: on });
  }
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'content-type': 'application/json',
      'access-control-allow-origin': '*',
    },
  });
}

function notConfigured(what: string): Response {
  // The dashboard was constructed without SessionsPaths (e.g. a legacy host
  // that doesn't track to disk). Return 503 so the client can surface a
  // helpful error rather than failing silently.
  return jsonResponse(
    { error: `${what} unavailable: dashboard not configured with event paths` },
    503,
  );
}

function round1(n: number): number {
  return Math.round(n * 10) / 10;
}
function round4(n: number): number {
  return Math.round(n * 10000) / 10000;
}

/** Server-side HTML escape for values we interpolate into the session-detail
 *  template. Kept tiny on purpose: we only emit text into attributes / text
 *  nodes, no rich markup. */
function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => {
    switch (c) {
      case '&': return '&amp;';
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '"': return '&quot;';
      default: return '&#39;';
    }
  });
}

/** Result of route-matching a dashboard URL. The legacy `kind` values
 *  (html/stats/recent/png) stay; new routes return a dedicated kind plus an
 *  optional sessionId for the dynamic /sessions/${id} + /api/sessions/${id}
 *  variants. */
export type DashboardRoute =
  | { kind: 'html' }
  | { kind: 'stats' } // /proxy-stats — legacy live counter
  | { kind: 'recent' } // /proxy-recent — legacy ring buffer
  | { kind: 'png' } // /proxy-latest-png
  | { kind: 'api-sessions' } // /api/sessions.json
  | { kind: 'api-session'; sessionId: string } // /api/sessions/${id}.json
  | { kind: 'api-disk' } // /api/disk.json
  | { kind: 'api-stats' } // /api/stats.json
  | { kind: 'api-prune' } // /api/sessions/prune (POST)
  | { kind: 'api-compression' } // /api/compression (POST {enabled}) — runtime kill switch
  | { kind: 'session-html'; sessionId: string }; // /sessions/${id}

/** Match dashboard paths (handle query strings on /proxy-latest-png). */
export function dashboardPath(pathname: string): DashboardRoute | null {
  if (pathname === '/' || pathname === '/dashboard') return { kind: 'html' };
  if (pathname === '/proxy-stats') return { kind: 'stats' };
  if (pathname === '/proxy-recent') return { kind: 'recent' };
  if (pathname === '/proxy-latest-png') return { kind: 'png' };
  if (pathname === '/api/sessions.json') return { kind: 'api-sessions' };
  if (pathname === '/api/disk.json') return { kind: 'api-disk' };
  if (pathname === '/api/stats.json') return { kind: 'api-stats' };
  if (pathname === '/api/sessions/prune') return { kind: 'api-prune' };
  if (pathname === '/api/compression') return { kind: 'api-compression' };
  // /api/sessions/${id}.json — id is [a-f0-9]{1,16} (sha8 prefix) plus
  // '<unknown>' literal. Reject anything else to keep paths sanitized.
  const apiSess = /^\/api\/sessions\/([A-Za-z0-9<>_-]{1,32})\.json$/.exec(pathname);
  if (apiSess) return { kind: 'api-session', sessionId: apiSess[1]! };
  const sessHtml = /^\/sessions\/([A-Za-z0-9<>_-]{1,32})$/.exec(pathname);
  if (sessHtml) return { kind: 'session-html', sessionId: sessHtml[1]! };
  return null;
}

// ---- inline HTML template -------------------------------------------------

const DASHBOARD_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>pixelpipe – Live dashboard</title>
<style>
  /* Pre-mount body styling so the loading flash matches the Svelte UI. The
     real stylesheet is injected by Svelte components on mount. */
  * { box-sizing: border-box; }
  body { margin: 0; padding: 0; background: #0d1117; color: #c9d1d9;
         font: 14px/1.45 -apple-system,BlinkMacSystemFont,"SF Mono",Menlo,monospace; }
  #app:empty::before { content: 'pixelpipe dashboard loading…';
                       display: block; padding: 24px; color: #6e7681; }
</style>
</head>
<body>
<div id="app"></div>
<script>${DASHBOARD_JS}</script>
</body></html>
`;

// ---- session detail HTML template ----------------------------------------
//
// Standalone page served at /sessions/${id}. Reuses the same dark theme as
// the main dashboard for visual continuity. The body content is one panel
// with the session header + an event table; data is fetched from
// /api/sessions/${id}.json on load. A checkbox toggles `?include_bodies=1`
// for privacy-sensitive 4xx body samples.

const SESSION_DETAIL_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>pixelpipe - session __SESSION_ID__</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; padding: 24px; background: #0d1117; color: #c9d1d9;
         font: 14px/1.45 -apple-system,BlinkMacSystemFont,"SF Mono",Menlo,monospace; }
  h1 { font-size: 18px; font-weight: 600; margin: 0 0 6px; letter-spacing: -0.01em; }
  a { color: #58a6ff; text-decoration: none; }
  a:hover { text-decoration: underline; }
  .sub { color: #6e7681; font-size: 12px; margin-bottom: 22px; }
  .panel { background: #161b22; border: 1px solid #30363d; border-radius: 10px;
           padding: 14px 16px; margin-bottom: 14px; }
  .meta { display: grid; grid-template-columns: 140px 1fr; gap: 4px 14px;
          font-size: 12px; }
  .meta .k { color: #6e7681; }
  .meta .v { color: #c9d1d9; word-break: break-all; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { text-align: left; color: #6e7681; font-weight: 500; padding: 6px 8px;
       border-bottom: 1px solid #30363d; }
  td { padding: 6px 8px; border-bottom: 1px solid #21262d; vertical-align: top;
       font-variant-numeric: tabular-nums; }
  td.num { text-align: right; }
  tr:last-child td { border-bottom: none; }
  .json-cell { color: #6e7681; max-width: 600px; overflow: hidden;
               text-overflow: ellipsis; white-space: nowrap; cursor: pointer; }
  .json-cell.open { white-space: pre-wrap; word-break: break-all; color: #c9d1d9; }
  .ctrls { display: flex; gap: 12px; align-items: center; margin: 14px 0; }
  .ctrls label { font-size: 12px; color: #6e7681; }
</style>
</head>
<body>
<h1><a href="/">pixelpipe</a> &rarr; session __SESSION_ID__</h1>
<div class="sub" id="header_sub">loading...</div>

<div class="panel">
  <div class="meta" id="meta"></div>
</div>

<div class="ctrls">
  <label><input type="checkbox" id="include_bodies"> include 4xx body samples (privacy: may contain raw user code)</label>
  <button type="button" id="del_btn" style="background:#21262d;color:#f85149;border:1px solid #30363d;padding:4px 12px;cursor:pointer;font-size:12px">delete this session</button>
</div>

<div class="panel">
  <table>
    <thead>
      <tr>
        <th>#</th><th>ts</th><th>status</th><th>path</th>
        <th class="num">orig chars</th><th class="num">img bytes</th>
        <th class="num">cache read</th><th>raw</th>
      </tr>
    </thead>
    <tbody id="ev_rows"></tbody>
  </table>
</div>

<script>
const SESSION_ID = '__SESSION_ID__';

function numFmt(n) {
  return (Math.round(Number(n) || 0)).toLocaleString();
}
function escapeHtml(s) {
  return String(s).replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
}
function fmtBytes(n) {
  if (!n) return '0 B';
  if (n < 1024) return n + ' B';
  if (n < 1024*1024) return (n/1024).toFixed(1) + ' KB';
  return (n/(1024*1024)).toFixed(1) + ' MB';
}

async function load() {
  const includeBodies = document.getElementById('include_bodies').checked;
  const url = '/api/sessions/' + encodeURIComponent(SESSION_ID) + '.json'
    + (includeBodies ? '?include_bodies=1' : '');
  let payload;
  try {
    payload = await fetch(url).then(r => r.json());
  } catch (e) {
    document.getElementById('header_sub').textContent = 'fetch error: ' + e.message;
    return;
  }
  if (payload.error) {
    document.getElementById('header_sub').textContent = payload.error;
    return;
  }
  const evs = payload.events || [];
  document.getElementById('header_sub').textContent =
    evs.length + ' events  -  ' + (includeBodies ? 'body samples shown' : 'body samples redacted');

  const meta = document.getElementById('meta');
  const cc = payload.claudeCode;
  const first = evs[0] || {};
  const last = evs[evs.length-1] || {};
  const metaRows = [
    ['session', SESSION_ID],
    ['events', evs.length],
    ['project (cwd)', first.cwd || '-'],
    ['first seen', first.ts || '-'],
    ['last seen', last.ts || '-'],
  ];
  if (cc) {
    metaRows.push(['claude code session', cc.sessionId]);
    metaRows.push(['claude code project', cc.projectPath]);
    metaRows.push(['first user preview', cc.firstUserPreview]);
  } else {
    metaRows.push(['claude code', 'no matching ~/.claude/projects/ session']);
  }
  meta.innerHTML = metaRows.map(([k, v]) =>
    '<div class="k">' + escapeHtml(String(k)) + '</div><div class="v">' + escapeHtml(String(v)) + '</div>'
  ).join('');

  const tbody = document.getElementById('ev_rows');
  tbody.innerHTML = evs.map((e, i) => {
    const cls = e.status >= 500 ? 'bad' : e.status >= 400 ? 'warn' : '';
    const raw = escapeHtml(JSON.stringify(e));
    return '<tr>'
      + '<td>' + (i+1) + '</td>'
      + '<td class="small">' + escapeHtml(String(e.ts || '')) + '</td>'
      + '<td class="' + cls + '">' + escapeHtml(String(e.status || '')) + '</td>'
      + '<td>' + escapeHtml(String(e.path || '')) + '</td>'
      + '<td class="num">' + numFmt(e.orig_chars) + '</td>'
      + '<td class="num">' + numFmt(e.image_bytes) + '</td>'
      + '<td class="num">' + numFmt(e.cache_read_tokens) + '</td>'
      + '<td><div class="json-cell" onclick="this.classList.toggle(\\'open\\')">' + raw + '</div></td>'
      + '</tr>';
  }).join('');
}

document.getElementById('include_bodies').addEventListener('change', load);
document.getElementById('del_btn').addEventListener('click', async () => {
  if (!window.confirm('Delete session ' + SESSION_ID + ' and all its events?\\n\\nThis cannot be undone.')) return;
  const r = await fetch('/api/sessions/prune', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ sessionId: SESSION_ID, force: true }),
  }).then(r => r.json());
  alert('removed ' + numFmt(r.eventsRemoved) + ' events, ' + fmtBytes(r.jsonlBytesFreed + r.sidecarBytesFreed));
  window.location.href = '/';
});
load();
</script>
</body></html>
`;
